node("") {
    stage("build") {
        git("https://github.com/vladflore/spring-transactions-demo.git")
        sh("./mvnw clean install")
    }
    stage("deploy") {
        echo("deploying the artifact")
    }
    stage("results") {
        junit("**/target/surefire-reports/TEST-*.xml")
        archive("target/*.jar")
    }
}